sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /r200_front/depth/points
    max_range: 4.0
    point_subsample: 10
    padding_offset: 0.1
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud_front
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /r200_right/depth/points
    max_range: 4.0
    point_subsample: 10
    padding_offset: 0.1
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud_right
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /r200_left/depth/points
    max_range: 4.0
    point_subsample: 10
    padding_offset: 0.1
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud_left